### ISSUE TITLE
[medium priority] Plots analysis results and put them into tables

### ISSUE THREAD

**Issue by echapon** [echapon/HiCharm2015#3]
Plots analysis results and put them into tables, using the files containing the fit results

**Comment by stahlleiton** [comment]
I can work on this and make a special version for the double ratios. I will use Emilien's macro "simplePrintResults.C" as a starting point. A summary of what I am planning to implement is:

1.) Given a path to a directory, list all the root files inside and add them to the vector of file paths.
2.) Then use the already made macro to loop over the files and extract the single and double ratios.
3.) If either the single or double ratio is missing (because it was done with simultaneous or separate fits), compute the missing variable using the other two.
4.) Put it in a text table following the same format as the other files (columns separated by semicolons with one line per bin).
